### ISSUE TITLE
Database Connection Issue

### ISSUE THREAD

**Issue by DrNevel** [sidataplus/omop-vocab-loader#2]
Hello everyone,

I've encountered an issue while following the instructions in the readme.md. I created a .env file in the same directory as the "load_vocab.py" script, entering all the required data with the provided structure from the readme.md file.

However, when running the "load_vocab.py" script, I encountered the following error:
`Database error while processing CONCEPT.csv: connection to server at "localhost" (::1), port XXXX failed: FATAL: password authentication failed for user "my_windows_user"`

It seems that the script is retrieving my Windows username ("my_windows_user") from the global system variables instead of using the PostgreSQL database username specified in the .env file.

While I understand this might be more related to Windows OS technicalities than the script itself, I hope that this issue could also help others experimenting with the OMOP schema in the future. Thanks!

**Comment by na399** [comment]
Hi @DrNevel, Thank you for your interest in our script and alerting the issue to us. 

The error appears to be due to our .env loading mechanism, which has now been fixed in #3. If your issue persists, please let us know.

By the way, our team has shifted to use [Sling](https://slingdata.io) to load vocab data into our OMOP database. Sling provides several robust database connections, and integration with [Dagster](https://dagster.io/blog/dagster-embedded-elt) orchestrator. Here are [the Sling+Dagster Python scripts](https://gist.github.com/na399/85bff15d6a4ba4ecc5bd28fe49f90b1a) that we use (as a part of our larger Dagster pipeline codebase). Given Sling can work independently without using Dagster, you may modify these Python codes to match your needs.

I hope these help. 
– Max

**Comment by DrNevel** [comment]
Thank you for the update! I'll check out all the proposed solutions, and I'll close the issue as soon as I'll have any feedback
